const fs = require('fs');
const path = require('path');
const packageJson = require('./package.json');

const version = packageJson.version;
const content = `// ⚠️ This file is auto-generated from package.json
// ⚠️ DO NOT EDIT THIS FILE DIRECTLY
// ⚠️ Update the "version" field in package.json instead
export const version = '${version}';
`;
const outputPath = path.join(__dirname, 'src', 'version.js');

try {
    fs.writeFileSync(outputPath, content);
    console.log(`✅ Updated src/version.js to v${version}`);
} catch (error) {
    console.error('❌ Error updating version.js:', error);
    process.exit(1);
}
